name: Update Github Stats Gist
on:
    workflow_dispatch:
    schedule:
        - cron: '0 */12 * * *'
    push:
        branches: master
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npx github-stats-box
              env:
                  GH_TOKEN: 9902fe7af76ad2ca43f3a3d0ec1ecabc
                  GIST_ID: 9902fe7af76ad2ca43f3a3d0ec1ecabc
                  ALL_COMMITS: true # If `true` it will count all commits, if `false` it will count your last year commits
                  K_FORMAT: false # If `true`, large numbers will be formatted with a "k", for example "1.5k"
